# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0451eb11631cbd79839c87b4fb4ff1c8aafbb43bd00eac91e185039e7b7f3380e63712713fd40e0c5243939c975688724ab0466273dc1abfcd400a3a74ba8fbe

test:
  secret_key_base: b3046f0a520d2c57a0c043ada99aef4526492beeb7a692e4d6e22bece954848243989d041a2bc4c4c1e98de213fe9f193aa23193787ea8d5a1beb866809badbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
